### ISSUE TITLE
Blank search no longer shows the admin flagged addons

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#369] opened 2015-12-22 07:16 UTC
I have noticed (for a while) that using the search button with blank query on the queue page no longer shows the admin flagged addons.

It seems that the problems is with `searching=` parameter

For example ..... 
Shows admin flagged:
`https://addons.mozilla.org/en-US/editors/queue/nominated?searching=True&text_query=&admin_review=1&application_id=&max_version=&waiting_time_days=#review-actions`

Doesn't show admin flagged:
`https://addons.mozilla.org/en-US/editors/queue/nominated?searching=&text_query=&admin_review=&application_id=&max_version=&waiting_time_days=`

Changing the `searching=&` to `searching=true&` fixes it.

**Comment by mstriemer** [comment] 2015-12-22 16:33
I can't reproduce this on dev or production. When I click the search button I see `searching=True` in the URL. It is [checking that it has a value set](https://github.com/mozilla/olympia/blob/d26f257d5c70c1ec745ca19047c2e1e9ee95d488/apps/editors/views.py#L404) but I don't know why it wouldn't be setting the value for you.

**Comment by mstriemer** [comment] 2015-12-22 16:35
Closing in favour of https://github.com/mozilla/olympia/issues/1137.

**Closed by mstriemer** 2015-12-22 16:35 UTC
